CREATE TABLE IF NOT EXISTS p0f (session TEXT NOT NULL,
                                first_seen TEXT NULL,
                                last_seen TEXT NULL,
                                uptime INTEGER NULL,
                                last_nat TEXT NULL,
                                last_chg TEXT NULL,
                                distance INTEGER NULL,
                                bad_sw INTEGER NULL,
                                os_name TEXT NULL,
                                os_flavor TEXT NULL,
                                os_match_q INTEGER NULL,
                                http_name TEXT NULL,
                                http_flavor TEXT NULL,
                                total_conn INTEGER NULL,
                                link_type TEXT NULL,
                                language TEXT NULL,
                                PRIMARY KEY(session))
